-- 作問・問い合わせフォームの保存先です。
-- Supabase SQL Editorで実行してください。
-- サイト側は submit_question_suggestion RPCだけを使って投稿します。
-- 投稿一覧は公開せず、管理者はSupabase Table Editorで確認します。

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.question_suggestions (
  id bigint generated by default as identity primary key,
  genre text not null,
  answer_format text not null check (answer_format in ('4択', '入力形式')),
  question_text text not null,
  answer_text text,
  notes text,
  contact text,
  client_id text,
  submitter_hash text,
  status text not null default 'new' check (status in ('new', 'reviewing', 'accepted', 'rejected')),
  admin_memo text,
  created_at timestamptz not null default now()
);

alter table public.question_suggestions add column if not exists client_id text;
alter table public.question_suggestions add column if not exists submitter_hash text;
alter table public.question_suggestions enable row level security;

revoke all on table public.question_suggestions from anon, authenticated;
revoke all on sequence public.question_suggestions_id_seq from anon, authenticated;

drop policy if exists "question suggestions are not publicly readable" on public.question_suggestions;

drop function if exists public.submit_question_suggestion(text, text, text, text, text, text);
drop function if exists public.submit_question_suggestion(text, text, text, text, text, text, text);
create or replace function public.submit_question_suggestion(
  p_genre text,
  p_answer_format text,
  p_question_text text,
  p_answer_text text default null,
  p_notes text default null,
  p_contact text default null,
  p_client_id text default null
)
returns table(id bigint, created_at timestamptz)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  inserted_id bigint;
  inserted_created_at timestamptz;
  headers jsonb;
  remote_ip text;
  user_agent text;
  normalized_client_id text;
  requester_hash text;
begin
  headers := coalesce(nullif(current_setting('request.headers', true), '')::jsonb, '{}'::jsonb);
  remote_ip := coalesce(
    headers ->> 'cf-connecting-ip',
    split_part(coalesce(headers ->> 'x-forwarded-for', ''), ',', 1),
    headers ->> 'x-real-ip',
    'unknown'
  );
  user_agent := left(coalesce(headers ->> 'user-agent', 'unknown'), 240);
  normalized_client_id := nullif(left(trim(coalesce(p_client_id, '')), 80), '');
  requester_hash := encode(
    digest(concat_ws('|', trim(remote_ip), user_agent, coalesce(normalized_client_id, '')), 'sha256'),
    'hex'
  );

  if p_question_text is null or length(trim(p_question_text)) < 4 then
    raise exception 'question suggestion is too short';
  end if;

  if length(trim(p_question_text)) > 3000 then
    raise exception 'question suggestion is too long';
  end if;

  if p_answer_format not in ('4択', '入力形式') then
    raise exception 'answer format must be 4択 or 入力形式';
  end if;

  if exists (
    select 1
    from public.question_suggestions recent
    where recent.submitter_hash = requester_hash
      and recent.created_at > now() - interval '30 seconds'
  ) then
    raise exception 'please wait before sending another suggestion';
  end if;

  if (
    select count(*)
    from public.question_suggestions recent
    where recent.submitter_hash = requester_hash
      and recent.created_at > now() - interval '1 hour'
  ) >= 10 then
    raise exception 'too many suggestions from this client';
  end if;

  if (
    select count(*)
    from public.question_suggestions recent
    where recent.submitter_hash = requester_hash
      and recent.created_at > now() - interval '1 day'
  ) >= 20 then
    raise exception 'daily suggestion limit reached';
  end if;

  if (
    select count(*)
    from public.question_suggestions recent
    where recent.created_at > now() - interval '1 hour'
  ) >= 120 then
    raise exception 'suggestion form is temporarily busy';
  end if;

  insert into public.question_suggestions (
    genre,
    answer_format,
    question_text,
    answer_text,
    notes,
    contact,
    client_id,
    submitter_hash
  )
  values (
    left(trim(coalesce(p_genre, 'その他')), 80),
    p_answer_format,
    left(trim(p_question_text), 3000),
    nullif(left(trim(coalesce(p_answer_text, '')), 1200), ''),
    nullif(left(trim(coalesce(p_notes, '')), 3000), ''),
    nullif(left(trim(coalesce(p_contact, '')), 120), ''),
    normalized_client_id,
    requester_hash
  )
  returning question_suggestions.id, question_suggestions.created_at
  into inserted_id, inserted_created_at;

  return query select inserted_id, inserted_created_at;
end;
$$;

grant execute on function public.submit_question_suggestion(text, text, text, text, text, text, text)
to anon, authenticated;

create index if not exists question_suggestions_status_created_idx
  on public.question_suggestions (status, created_at desc);

create index if not exists question_suggestions_hash_created_idx
  on public.question_suggestions (submitter_hash, created_at desc);

create index if not exists question_suggestions_created_idx
  on public.question_suggestions (created_at desc);
